### ISSUE TITLE
Pro Keys Trainer (learn an instrument) crashes if it is the first thing entered in a session. Works if qp game is entered first

### ISSUE THREAD

**Issue by clwalker85** [hmxmilohax/rock-band-3-deluxe#471]
I was able to reproduce an issue similar to the [recently fixed pro guitar trainer bug](https://github.com/hmxmilohax/rock-band-3-deluxe/issues/423) with the pro keys trainer, where the trainer would crash upon the first missed key. RPCS3 would show an error log of "Access violation reading location". I would not get the error if quick play is used first. I didn't notice any of the other problems in the [screenshot for the pro guitar bug](https://github.com/hmxmilohax/rock-band-3-deluxe/issues/423).

I recently set this up with the latest version of RPCS3 and RB3DX, with the [Quick Configuration recommended settings from the RB3-PC Github README](https://github.com/carlmylo/rb3-pc/#quick-configuration) applied. I was also playing with a Wii MIDI Adapter (with the jumper resistor pulled off to imitate a PS3 adapter instead) and a Wii keyboard hooked up to the MIDI input, if it matters.

**Comment by jnackmclain** [comment]
fixed on develop branch with [e86581b](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/e86581b11bbf9517991028612cf5c306f9e7d958)

**Comment by jnackmclain** [comment]
actually i should say i think i did

**Comment by clwalker85** [comment]
Tested with the [develop beta build](https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/develop) and got the same error, except this time the error occurs before I can even begin any tutorial:

```F {PPU[0x1000000] Thread (main_thread) [0x008f30b0]} VM: Access violation reading location 0x8 (unmapped memory)```

Installing the [latest stable build](https://nightly.link/hmxmilohax/rock-band-3-deluxe/workflows/build/main/RB3DX-PS3.zip) reverts it back to erroring on the first missed note in any tutorial.

**Comment by jnackmclain** [comment]
this was fixed at some point

**Comment by clwalker85** [comment]
This appears to be somewhat fixed, it doesn't freeze on the first missed key. However, I can still reproduce a very similar issue after a couple of lessons. Instead of freezing, the track plays catch up and sometimes has the same track playing on top of itself. It makes it impossible to complete most trainings. See these videos for examples:

https://drive.google.com/file/d/1nmyxfjwvPNeXy3KJ5lZRxKEvRU5n6KLy/view?usp=sharing

https://drive.google.com/file/d/1niW9s8JZBLK_7Bwp7Po8OfHxK1_m6zvh/view?usp=sharing
