### ISSUE TITLE
Ingame customizer overshell renders off-screen on vocals

### ISSUE THREAD

**Issue by lunalawl** [hmxmilohax/rock-band-3-deluxe#495]

**Comment by jnackmclain** [comment]
this was also fixed at some point

**Comment by LightningXCE** [comment]
This is still broken on latest nightly. If you only have a single vocal controller joined and enter the customizer, the menu does not appear on-screen

Sorry :(

**Comment by jnackmclain** [comment]
did you press start?
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/a87cf39f-28f0-4563-9cbc-b9822b06aa0e)

**Comment by jnackmclain** [comment]
rb3e issue

**Comment by jnackmclain** [comment]
truly fixed via 65d6d545eafab7c99d2c339164292b9a1bd71910

**Comment by jnackmclain** [comment]
I figured out why this happens and this is solely a rb3e issue I cannot fix
https://github.com/RBEnhanced/RB3Enhanced/issues/20
