### ISSUE TITLE
Venue lights and camera bugged for keys-upgraded songs (again)

### ISSUE THREAD

**Issue by SonicSBL** [hmxmilohax/rock-band-3-deluxe#755]
**Describe the bug**
I hate to bring this up again, but we're back to square one with venues and keys upgrades. See #663 for a description.

**To Reproduce**
1. Play any legacy song with keys upgrades (ex. Summer of '69)
2. See flashing lights at various times and a fast wave of camera cuts near the end (on some songs, such as the above example, the camera may get stuck on the drummer showing off instead of playing)

**Expected behavior**
Lights and camera should be similar to the vanilla song.

**Screenshots**
N/A

**DX Settings**
- [dx_modifiers.txt](https://github.com/user-attachments/files/16045990/dx_modifiers.txt)
- [dx_settings.txt](https://github.com/user-attachments/files/16045991/dx_settings.txt)
- [dx_values.txt](https://github.com/user-attachments/files/16045995/dx_values.txt)

**Game Information**
 - Platform: PS3 HW
 - Version: eg. 1.1.0-nightly (33EEC2E)
 - Song Count: 672

**Additional context**
The practice metronome previously described is unaffected.

**Comment by jnackmclain** [comment]
Yeah im midway through working on it. stick to beta10 for now there is a lot to go through but it will be fixed

**Comment by jnackmclain** [comment]
also the camera spam i cannot figure out

**Comment by jnackmclain** [comment]
Static camera issues should be resolved in latest nightly. Still trying to nail down why the camera spam and strobing happens

**Comment by SonicSBL** [comment]
I looked into this a little more by comparing the camera cuts from the original MIDI with the venue in Deluxe. One thing I saw is that some regular cuts don't appear in DX when they're supposed to. They don't show up at all until the spam. After that, the venue is pretty much how it should be.

I also found camera spam in We Are the Champions (RB3 version), which makes me think it's present in other official RB3 versions too.

**Comment by SonicSBL** [comment]
It seems that even with upgrades that had their venue track cleaned in Nautilus, these issues are still present. I saw it in my own upgrades.

**Comment by jnackmclain** [comment]
Camera spam is fixed in latest nightly for real this time
